version: '3'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ribbit-web
    command: python manage.py runserver localhost:$PORT
    volumes:
      - .:/ribbit
    ports:
      - "localhost:$PORT"